In [ ]:
# To launch Jupyter Notebook in the current project, run this command in the terminal:
# python -m ipykernel install --user --name myenv
# and select 'entan-mkdocs' as kernel in the Jupyter Notebook interface.

In [5]:
import libs.minio as minio
minio.minio_client = minio.create_minio_client()
gongs_df = minio.get_center_temp_df("Testx", "gongs")
times_df = minio.get_center_temp_df("Testx", "timetables")
struct_df = minio.get_center_temp_df("Testx", "periods_struct")

In [11]:
struct_df
struct_df_h = struct_df.set_index("period_type")
struct_df_h10 = struct_df_h.loc["10 days"]
struct_df_h10

             day       day_type
period_type
10 days        0          day 0
10 days        1      start day
10 days        2     course day
10 days        3     course day
10 days        4  vipassana day
10 days        5     course day
10 days        6     course day
10 days        7     course day
10 days        8     course day
10 days        9     course day
10 days       10      metta day
10 days       11       last day

In [14]:
times_df_h = times_df.set_index(["period_type", "day_type"])
times_df_h10 = times_df_h.loc["10 days", "course day"]
times_df_h10

C:\Users\spego\AppData\Local\Temp\ipykernel_24184\2046159222.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  times_df_h10 = times_df_h.loc["10 days", "course day"]

                         time  gong_id  auto targets  comment
period_type day_type
10 days     course day  04:00        3     1      CC     None
            course day  04:20        2     1      CC     None
            course day  06:30        4     0      CC  Cuisine
            course day  07:50        3     1      CC     None
            course day  09:07        2     1      CC     None
            course day  11:00        4     0      CC  Cuisine
            course day  12:50        3     1      CC     None
            course day  14:15        1     1      CC     None
            course day  14:20        2     1      CC     None
            course day  15:37        1     1      CC     None
            course day  17:00        4     0      CC  Cuisine
            course day  17:50        3     1      CC     None
            course day  19:07        1     1      CC     None
            course day  20:30        2     0      CC  Servant